### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by JihyunKiminGithub** [daviddaiweizhang/istar#1]
Dear author,
Thank you for creating this awesome tool.

While running the run.sh script, I encountered an IndexError. Could you please take a look at my errors and provide some advice? If necessary, I am more than willing to share my dataset with you.

Thank you in advance,
Jihyun.

<img width="452" alt="image" src="https://github.com/daviddaiweizhang/istar/assets/105287433/847f9f1b-af56-43d9-b060-e7f8f32416b6">

**Comment by daviddaiweizhang** [comment]
Hi Jihyun,

Thank you for trying iStar. Could you check your `locs.tsv` and see whether any spots are beyond the histology image boundary? The maximal `x` and `y` coordinates in `locs.tsv` should not exceed `width - radius` and `height - radius`, respectively, where `width` and `height` are the dimension of `he.jpg`, and `radius` is the value in `radius.txt`.

David

**Comment by JihyunKiminGithub** [comment]
Dear author,

Thank you for your prompt response.
I would like to clarify that as I am using the filtered_feature_bc_matrix.h5, there should be no spots beyond the histology image boundary.
If I provide you with the data, could you please check my inputs for iStar?

Thank you in advance.

Best regards,
Jihyun.

**Comment by daviddaiweizhang** [comment]
Hi Jihyun,

Even though the raw data should have no problems, errors can come into play during the process of converting the raw data to the input formats of iStar. I have seen examples like this in the past, and thus it would be really helpful if you could check the dimension of your `he.jpg` and the maximal values of `x` column and `y` column ` in `locs.tsv`, so that we can check whether the basic things are correct. These values are straightforward to check and would make debugging easier.

Thank you.

David

**Comment by echen0117** [comment]
Hi David,

I'm having the same problem as Jihyun. My dimensions of he.jpg are 768 x 768 pixels and before running the rescale function, I'm taking the array_row and array_col values to put into x and y of locs-raw.tsv. When I do this, the max x and y of locs.tsv are 38 and 66 respectively. When I tried it previously with pxl_row_in_fullres and pxl_col_in_fullres values, I got the same error with larger x and y values (on the order of 13000). My radius is 36 if that helps.

Thanks,
Liz

**Comment by daviddaiweizhang** [comment]
Hi @echen0117 ,

Thank you for the feedback. I suppose you are using a Visium dataset? There are two possible causes of this error.

1. Please make sure you are using `y = pxl_row_in_fullres` and `x = pxl_col_in_fullres`. Swapping `x` and `y` by accident is one of the most common causes of errors when using istar.

2. If your `x` and `y` are correct, does your `spatial/cytassist_image.tiff` and `spatial/tissue_hires_image.png` correspond to two different image histology images? If that is the case, Space Ranger automatically registers the two and generates `spatial/aligned_tissue_image.jpg`. Their registration algorithm is not perfect and might map some spots outside the full resolution image's boundary. I am working on a new version of the software package to handle this issue.

**Comment by echen0117** [comment]
Hi @daviddaiweizhang,

Thanks for your feedback. I have verified that my x and y are correct. My cytassist_image.tiff IS different from my hires_image. It looks like it's been rotated 90 degrees left and then flipped horizontally from the tissue_hires_image.jpg. I do have an aligned_tissue_image.jpg file that looks like the hires image. Unfortunately, I'm still getting the same error:

Traceback (most recent call last):
  File "/Users/eychen/Downloads/istar-master/impute.py", line 411, in <module>
    main()
  File "/Users/eychen/Downloads/istar-master/impute.py", line 401, in main
    impute(
  File "/Users/eychen/Downloads/istar-master/impute.py", line 353, in impute
    out_list = [get_model_kwargs(kwargs) for kwargs in kwargs_list]
  File "/Users/eychen/Downloads/istar-master/impute.py", line 353, in <listcomp>
    out_list = [get_model_kwargs(kwargs) for kwargs in kwargs_list]
  File "/Users/eychen/Downloads/istar-master/impute.py", line 195, in get_model_kwargs
    return get_model(**kwargs)
  File "/Users/eychen/Downloads/istar-master/impute.py", line 206, in get_model
    dataset = SpotDataset(x, y, locs, radius)
  File "/Users/eychen/Downloads/istar-master/impute.py", line 103, in __init__
    x = get_patches_flat(x_all, locs, mask)
  File "/Users/eychen/Downloads/istar-master/impute.py", line 154, in get_patches_flat
    x = patch[mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 7

I'll wait for the new version, thanks.
Liz

**Comment by yameichen531** [comment]
Hi @echen0117 ,

I encountered the same issue you posted about. Following David's previous responses, I discovered that my coordinates in loc-raw.tsv didn't align with the dimensions of the he-raw.jpg I used. Here's how I addressed it:

In my case, I was working with Visium data, and I used the image when I used as INPUT when running Space Ranger. Then the results were accurate and made sense. I encountered the error when using the image from the outputs of Space Ranger. I recommend checking the dimensions of your image (in the info of the image file) and ensuring that your coordinates fall within the range.

Thanks,
Yamei

**Comment by ryland-mortlock** [comment]
Hi, just adding on. I ran into the same issue as @JihyunKiminGithub and @echen0117 
I double-checked I was using using `y = pxl_row_in_fullres` and `x = pxl_col_in_fullres` as directed by @daviddaiweizhang 
And notice that the maximum values in locs.tsv was still exceeding the dimensions of he.jpg leading to the same index error as above
My data is from visium, and just like @echen0117 I notice my cytassist_image.tiff is different from my hires_image, also rotated.
I followed the advice of @yameichen531 and used the .tiff image which was fed in to Space Ranger rather than the tissue_highres.png which came out of space ranger, and it worked! Thanks @yameichen531 !
Based on this, it seems the pxl_row_in_fullres and pxl_col_in_fullres from the spatial/tissue_positions.csv output of Space Ranger corresponds to the original input (full-resolution) image not the tissue_highres image which is output by Space Ranger.

**Comment by echen0117** [comment]
Used the original image and it works now. Thanks @ryland-mortlock and @yameichen531!

**Comment by DHUXU** [comment]
> Used the original image and it works now. Thanks @ryland-mortlock and @yameichen531!
Hi   @daviddaiweizhang， @ryland-mortlock  ， @echen0117 ，
I would like to ask you a question, that is, in my work, I only need to extract the features of the image and then run the **_impute_by_basic.py_** to align the features with the spot, but when using data other than the demo here, I get an IndexError, and I tried to set the **_cytassist_image.tiff_** and **_tissue_hires_image.png_** separately  as **_he-raw.jpg_**, and the **_radius-raw_** and _**pixel-size-raw**_ are calculated according to the operations in the readme file, and the _**pxl_row_in_fullres**_ and _**pxl_col_in_fullres**_ in the _**tissue_positions.csv**_ file are extracted as the contents of _**locs.tsv**_, and the features are extracted and run _**impute_by_ basic.py**_ still get an IndexError. How can this be resolved, I would appreciate your advice.

**Comment by DHUXU** [comment]
> Hi, just adding on. I ran into the same issue as @JihyunKiminGithub and @echen0117 I double-checked I was using using `y = pxl_row_in_fullres` and `x = pxl_col_in_fullres` as directed by @daviddaiweizhang And notice that the maximum values in locs.tsv was still exceeding the dimensions of he.jpg leading to the same index error as above My data is from visium, and just like @echen0117 I notice my cytassist_image.tiff is different from my hires_image, also rotated. I followed the advice of @yameichen531 and used the .tiff image which was fed in to Space Ranger rather than the tissue_highres.png which came out of space ranger, and it worked! Thanks @yameichen531 ! Based on this, it seems the pxl_row_in_fullres and pxl_col_in_fullres from the spatial/tissue_positions.csv output of Space Ranger corresponds to the original input (full-resolution) image not the tissue_highres image which is output by Space Ranger.

Used the original image and it works now. Thanks @ryland-mortlock and @yameichen531!
Hi @daviddaiweizhang， @ryland-mortlock ， @echen0117 ，
I would like to ask you a question, that is, in my work, I only need to extract the features of the image and then run the impute_by_basic.py to align the features with the spot, but when using data other than the demo here, I get an IndexError, and I tried to set the cytassist_image.tiff and tissue_hires_image.png separately as he-raw.jpg, and the radius-raw and pixel-size-raw are calculated according to the operations in the readme file, and the pxl_row_in_fullres and pxl_col_in_fullres in the tissue_positions.csv file are extracted as the contents of locs.tsv, and the features are extracted and run **_impute_by basic.py_** still get an IndexError. How can this be resolved, I would appreciate your advice.
![Uploading 屏幕截图 2024-04-06 151605.png…]()

**Comment by DHUXU** [comment]
> Hi, just adding on. I ran into the same issue as @JihyunKiminGithub and @echen0117 I double-checked I was using using `y = pxl_row_in_fullres` and `x = pxl_col_in_fullres` as directed by @daviddaiweizhang And notice that the maximum values in locs.tsv was still exceeding the dimensions of he.jpg leading to the same index error as above My data is from visium, and just like @echen0117 I notice my cytassist_image.tiff is different from my hires_image, also rotated. I followed the advice of @yameichen531 and used the .tiff image which was fed in to Space Ranger rather than the tissue_highres.png which came out of space ranger, and it worked! Thanks @yameichen531 ! Based on this, it seems the pxl_row_in_fullres and pxl_col_in_fullres from the spatial/tissue_positions.csv output of Space Ranger corresponds to the original input (full-resolution) image not the tissue_highres image which is output by Space Ranger.

Hi @daviddaiweizhang， @ryland-mortlock ， @echen0117 ，
I would like to ask you a question, that is, in my work, I only need to extract the features of the image and then run the impute_by_basic.py to align the features with the spot, but when using data other than the demo here, I get an IndexError, and I tried to set the cytassist_image.tiff and tissue_hires_image.png separately as he-raw.jpg, and the radius-raw and pixel-size-raw are calculated according to the operations in the readme file, and the pxl_row_in_fullres and pxl_col_in_fullres in the tissue_positions.csv file are extracted as the contents of locs.tsv, and the features are extracted and run impute_by basic.py still get an IndexError. How can this be resolved, I would appreciate your advice.
![屏幕截图 2024-04-06 151605](https://github.com/daviddaiweizhang/istar/assets/166201989/2101c865-b659-49b8-9121-63d0a3b6cbd8)

**Comment by JihyunKiminGithub** [comment]
My original error was solved by using tiff file.
I changed the file into a jpg!

Thank you @ryland-mortlock @daviddaiweizhang

**Comment by jw235** [comment]
Hello everyone,

I am encountering a problem using Xenium data in my pipeline. The demo runs fine, but as soon as I insert my own HE-raw.jpg images, I keep getting the same Boolean error that JihyunKiminGithub has also reported.

Details about my data:

Dimensions of the HE-raw.jpg: (6777, 4183)
Maximum value in the 'x' column: 5595.84542857143
Maximum value in the 'y' column: 3846.732628571429
Error description:
The error I’m encountering seems identical to the one described by XY. The analysis fails, and there is no clear indication of how I can resolve the issue.

Questions:

Is there a known solution to this Boolean error, especially when using Xenium data?
How should I select the radius and pixelsize to avoid this error, particularly given the image dimensions and values mentioned above?
What adjustments are necessary to ensure that the pipeline runs smoothly with Xenium data?
How can I adjust the number of clusters?
What should go into the gene-names.txt file? Are these marker genes for the clusters?
Any guidance or suggestions to help resolve this issue would be greatly appreciated, as I depend on this analysis.

Thank you in advance for your support!

Best regards, Justus

**Comment by AotaoCN** [comment]
> My original error was solved by using tiff file.我原来的错误是用 tiff 文件解决的。 I changed the file into a jpg! 我把文件改成 jpg 了！
> 
> Thank you   谢谢你 [@ryland-mortlock](https://github.com/ryland-mortlock) [@daviddaiweizhang](https://github.com/daviddaiweizhang)

Hello, could you please elaborate on how to prepare the input file for istar using 10× data?

**Comment by AotaoCN** [comment]
@daviddaiweizhang @echen0117
