### ISSUE TITLE
No such file or directory: 'data/markers/celltype.tsv'

### ISSUE THREAD

**Issue by JihyunKiminGithub** [daviddaiweizhang/istar#17]
Dear author,

I ran the iStar code (run.sh ./s4/) in my server and it ran a long time and suddenly showed an error.
Since it is hard to go upstream to the log, I am wondering why I have this error.

Thank you in advance,
Jihyun

./s4/spots/THOC3.png
./s4/spots/SSB.png
./s4/spots/ATP11B.png
./s4/spots/GSTM3.png
./s4/spots/MMADHC.png
./s4/spots/CHPF.png
./s4/spots/SOX4.png
./s4/spots/GLO1.png
./s4/spots/VWA1.png
./s4/spots/SEC13.png
./s4/spots/SNX9.png
./s4/spots/PPP1R18.png
./s4/spots/ESYT2.png
./s4/spots/SEMA4D.png
Traceback (most recent call last):
  File "/home/jovyan/work/istar_jk/pixannot.py", line 115, in <module>
    main()
  File "/home/jovyan/work/istar_jk/pixannot.py", line 94, in main
    scores, lab_names = get_scores(prefix_inp, marker_file)
  File "/home/jovyan/work/istar_jk/pixannot.py", line 30, in get_scores
    df = load_tsv(marker_file, index=False)
  File "/home/jovyan/work/istar_jk/utils.py", line 86, in load_tsv
    df = pd.read_csv(filename, sep='\t', header=0, index_col=index_col)
  File "/opt/conda/envs/iStar/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/iStar/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/envs/iStar/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/envs/iStar/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/envs/iStar/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/markers/celltype.tsv'

**Comment by JihyunKiminGithub** [comment]
I think I found a solution to this question.
