### ISSUE TITLE
Inverse of tissue mask

### ISSUE THREAD

**Issue by cherrie-g** [daviddaiweizhang/istar#26]
Hi
I applied iStar to a H&E image, and in the step ·get_mask.py· I got an error and an inverse tissue mask.
The error is:
```
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fd6d594a940>
Traceback (most recent call last):
  File "/miniconda/envs/st/lib/python3.9/site-packages/threadpoolctl-2.2.0-py3.9.egg/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/miniconda/envs/st/lib/python3.9/site-packages/threadpoolctl-2.2.0-py3.9.egg/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/miniconda/envs/st/lib/python3.9/site-packages/threadpoolctl-2.2.0-py3.9.egg/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/miniconda/envs/st/lib/python3.9/site-packages/threadpoolctl-2.2.0-py3.9.egg/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
```
The ·mask-small.png· is like below where the black region is tissue.
![image](https://github.com/user-attachments/assets/e95923b1-c189-4fd8-8055-889c7b29ffaf)

Please help to find out what's wrong.

**Comment by zwl8620** [comment]
I tested two samples and found the same problem. I checked the code of get_mask.py and didn't know how to solve it. Can you give us some advice? Thanks you! @daviddaiweizhang 
![mask-small](https://github.com/user-attachments/assets/3c5bd8b6-693c-46a6-b06a-d2152c91d69b)

**Comment by qiuyinong2** [comment]
@cherrie-g 
Hello, I would like to ask about data preprocessing and how to generate the standard input format required by ISTAR, that is, how to generate two txt files.
