### ISSUE TITLE
IndexError: boolean index did not match indexed array along axis 1; size of axis is 0 but size of corresponding boolean axis is 27

### ISSUE THREAD

**Issue by linch233** [daviddaiweizhang/istar#29]
![屏幕截图 2024-12-02 164632](https://github.com/user-attachments/assets/23e643f0-210e-44a6-90c7-126e7a7e61da)
"Dear Professor, thank you for your work. However, I encountered an error in the image when I'm using, which says 'IndexError: boolean index did not match indexed array along axis 1; size of axis is 0 but size of corresponding boolean axis is 27'. Could you please tell me what might have caused this and how to avoid it?"

**Comment by yxs-124** [comment]
> ![屏幕截图 2024-12-02 164632](https://github.com/user-attachments/assets/23e643f0-210e-44a6-90c7-126e7a7e61da)“亲爱的教授，感谢您的工作。但是，我在使用时在图像中遇到了一个错误，它说 'IndexError： boolean index did not match indexed array along axis 1;轴的大小为 0，但相应的布尔轴的大小为 27'。您能告诉我是什么原因造成的，以及如何避免它吗？

Hello, I wonder if your problem has been solved now? I had the same problem.

**Comment by baixvwyl** [comment]
请问解决了吗？我有相同问题Smoothening cls embeddings...
runtime: 1
Smoothening sub embeddings...
runtime: 0
Saving embeddings...
NASH-HCC/embeddings-hist.pickle
22 sec
Embeddings saved to NASH-HCC/embeddings-hist.pickle
Pickle loaded from NASH-HCC/embeddings-hist.pickle
Clustering pixels using km...
(553472, 579)
/root/miniconda3/envs/iSTAR/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
17 sec
n_clusters: 2
NASH-HCC/mask-small.png
Dataframe loaded from NASH-HCC/cnts.tsv
NASH-HCC/gene-names.txt
Dataframe loaded from NASH-HCC/locs-raw.tsv
NASH-HCC/locs.tsv
NASH-HCC/radius.txt
Dataframe loaded from NASH-HCC/cnts.tsv
Pickle loaded from NASH-HCC/embeddings-hist.pickle
Dataframe loaded from NASH-HCC/locs.tsv
Image loaded from NASH-HCC/he.jpg
x: (784, 768, 579) , y: (1987, 1000)
Traceback (most recent call last):
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 411, in <module>
    main()
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 401, in main
    impute(
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 353, in impute
    out_list = [get_model_kwargs(kwargs) for kwargs in kwargs_list]
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 353, in <listcomp>
    out_list = [get_model_kwargs(kwargs) for kwargs in kwargs_list]
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 195, in get_model_kwargs
    return get_model(**kwargs)
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 206, in get_model
    dataset = SpotDataset(x, y, locs, radius)
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 103, in __init__
    x = get_patches_flat(x_all, locs, mask)
  File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 154, in get_patches_flat
    x = patch[mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 71

**Comment by linch233** [comment]
> 请问解决了吗？我有相同问题Smoothening cls embeddings... runtime: 1 Smoothening sub embeddings... runtime: 0 Saving embeddings... NASH-HCC/embeddings-hist.pickle 22 sec Embeddings saved to NASH-HCC/embeddings-hist.pickle Pickle loaded from NASH-HCC/embeddings-hist.pickle Clustering pixels using km... (553472, 579) /root/miniconda3/envs/iSTAR/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning super()._check_params_vs_input(X, default_n_init=10) 17 sec n_clusters: 2 NASH-HCC/mask-small.png Dataframe loaded from NASH-HCC/cnts.tsv NASH-HCC/gene-names.txt Dataframe loaded from NASH-HCC/locs-raw.tsv NASH-HCC/locs.tsv NASH-HCC/radius.txt Dataframe loaded from NASH-HCC/cnts.tsv Pickle loaded from NASH-HCC/embeddings-hist.pickle Dataframe loaded from NASH-HCC/locs.tsv Image loaded from NASH-HCC/he.jpg x: (784, 768, 579) , y: (1987, 1000) Traceback (most recent call last): File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 411, in main() File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 401, in main impute( File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 353, in impute out_list = [get_model_kwargs(kwargs) for kwargs in kwargs_list] File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 353, in out_list = [get_model_kwargs(kwargs) for kwargs in kwargs_list] File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 195, in get_model_kwargs return get_model(**kwargs) File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 206, in get_model dataset = SpotDataset(x, y, locs, radius) File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 103, in **init** x = get_patches_flat(x_all, locs, mask) File "/mnt/e/NASH-HCC单细胞/ST/data/iSTAR_data/iSTAR_input/impute.py", line 154, in get_patches_flat x = patch[mask] IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 71

没有彻底解决，有的样本对HE重新裁剪之后解决了，有的还是这样的报错
